title: Cristiano Cabrera
description: Mechanical Engineer and Machine Drafter
site_title: 'Cristiano Cabrera'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: cmcabrera97
blog_url: https://www.linkedin.com/in/cristiano-cabrera/
email: cristiano.cabrera@gmail.com
keybase_username: N/A
twitter_username: N/A
reddit_username: N/A

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
